### ISSUE TITLE
AAL file construction question.

### ISSUE THREAD

**Issue by jlhanson5** [ntustison/BrianSccanTutorial#1]
Hello Nick and others,

My lab group was working through your tutorial, and we were just starting to attempt to use SCCAN approaches with our own data. We understood how all the steps work, but wondered about how to generate the appropriate input files? Basically, we were going to switch out pbac_train_img.mha and pbac_test_img.mha, but weren't clear on how these files were constructed. I tried to simply input a nifti file, but wasn't sure how to reduce it down to 2-dimensions (so it could be used as a matrix in the code). Do folks have suggestions about a straight-forward way to do that for a multitude of subjects? Any advice is greatly appreciated! 
 
Thanks much!
Jamie.

**Comment by ntustison** [comment]
Hi Jamie,

Those are the 2-D images where the "rows" of the 2-D image are the N subjects and each "column" corresponds to a single spatial point in the cortical mask defined in the template space.  It's a convenient way to store multiple-subject data while minimizing the amount of space required for storage.

Nick

**Comment by ntustison** [comment]
Brian has created multiple tools for creating such images from multiple subjects and going between lists of images and this type of storage format.

**Comment by ntustison** [comment]
Brian has created multiple tools for creating such images from multiple subjects and going between lists of images and this type of storage format.
